import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Matching.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ready, Set, STEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <video
            src={require('../../public/wordmatch-interview.mp4')}
            autoPlay
          />
        </div>
      </main>
    </div>
  );
}
