import Head from 'next/head';
import styles from '../../styles/Matching.module.css';
import { useState } from 'react';

const planetData = [
  {
    question:
      'Does not have any moons or rings, your weight on this planet would be 38% of your weight on earth, a year on this planet is 88 days',
    correct: 'Mercury',
    answers: ['Venus', 'Mars', 'Earth', 'Mercury'],
    video: '../../public/video-bg.mp4',
  },
  {
    question:
      'Does not have any moons or rings, a day on this planet is longer than a year, the hottest planet in our solar system',
    correct: 'Venus',
    answers: ['Mercury', 'Mars', 'Earth', 'Venus'],
  },
  {
    question:
      'Only planet not to be named after a Greek or Roman deity, it was formed 4.54 billion years ago, the densest planet in the solar system',
    correct: 'Earth',
    answers: ['Venus', 'Mars', 'Neptune', 'Earth'],
  },
  {
    question:
      'Home to the tallest mountain in the solar system (Olympus Mons), has the largest dust storms in the solar system, has 2 small moons (Phobos and Deimos)',
    correct: 'Mars',
    answers: ['Venus', 'Jupiter', 'Earth', 'Mars'],
  },
];

export default function Home() {
  const [correctCount, setCorrectCount] = useState(0);
  console.log(Math.floor(Math.random() * planetData.length));
  return (
    <div className={styles.container}>
      <Head>
        <title>Ready, Set, STEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.planetsMain}>
        <div className={styles.planetsQuestion}>
          <h1>{planetData[0].question}</h1>
        </div>
        <div className={styles.planetsAnswers}>
          {planetData[0].answers.map((ans) => {
            return <button key={ans}>{ans}</button>;
          })}
        </div>
      </main>
    </div>
  );
}
