import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ready, Set, STEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.homeHeader}>
          <div>
            <h1>Ready, Set, STEM</h1>
          </div>
          <div>
            <ul className={styles.linksList}>
              <li className={styles.linkItem}>
                <Link href="/community">
                  <button className={styles.linkButton}>Community</button>
                </Link>
              </li>
              <li className={styles.linkItem}>
                <Link href="/bootcamps">
                  <button className={styles.linkButton}>Bootcamps</button>
                </Link>
              </li>
              <li className={styles.linkItem}>
                <Link href="/games">
                  <button className={styles.linkButton}>Games</button>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}
