import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ready, Set, STEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <video autoPlay loop muted className="w-full h-screen z-10">
          <source src="../public/video-bg.mp4" type="video/mp4" />
        </video>
        <div>
          <h1>Ready, Set, STEM</h1>
        </div>
        <div>
          <Link href="/1-5">
            <button className={styles.button}>1-5</button>
          </Link>
          <Link href="/6-8">
            <button className={styles.button}>6-8</button>
          </Link>
          <Link href="/9-12">
            <button className={styles.button}>9-12</button>
          </Link>
        </div>
      </main>
    </div>
  );
}
